menuThemeTrigger.addEventListener("click", showingMenu);
sailorDay.addEventListener("click", dayTheme);
sailorNight.addEventListener("click", darkTheme);
input_box.addEventListener("keyup", gettingSuggestions);
input_box.addEventListener("keyup", checkingifEmptyInput);
input_box.addEventListener("click",checkingifEmptyInput);
first_search_div.addEventListener("click", selectingAnOption);
second_search_div.addEventListener("click", selectingAnOption);
third_search_div.addEventListener("click", selectingAnOption);
searchButton.addEventListener("click",searchingGifs);
myGifText.addEventListener("click",myGifos);